### ISSUE TITLE
Why does v0.19.0 not support Ruby 2?

### ISSUE THREAD

**Issue by hsw15192617273** [zeebe-io/zeebe-client-ruby#84]
I need to use the `variables` parameter in `ThrowErrorRequest` in version v0.19.0, but I found that this version has a minimum requirement of Ruby 3.0, while I am using Ruby 2.7

May I know the reason behind the requirement of Ruby 3 for v0.19.0?

**Comment by cmur2** [comment]
Version https://github.com/zeebe-io/zeebe-client-ruby/releases/tag/v0.19.0 of this gem was released on 5th of June 2023.

Ruby 2.7 is end-of-life since March 2023, see https://endoflife.date/ruby

This means the authors of Ruby don't support Ruby 2 anymore as of March so it is reasonable to drop support as well for this gem.
